### ISSUE TITLE
Add Apache v2 license

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-ui#16]
- [x] Add top-level [`LICENSE`](http://www.apache.org/licenses/LICENSE-2.0) file.
- [x] Add the modified license header to the `LICENSE` file ([example](https://github.com/docker/docker/blob/master/LICENSE))
- [x] ~~Add [license header](https://www.apache.org/legal/src-headers.html#headers) to each source file excluding third-party dependencies.~~
- [x] Add top-level [`NOTICE`](https://www.apache.org/legal/src-headers.html#notice) file. This file is also used to specify the licenses of third-party dependencies that are distributed as part of our code (see also #15)
- [x] Reference both, `LICENSE` and `NOTICE`, in `README.md`.

See https://www.apache.org/legal/src-headers.html for a general discussion and FAQs.

**Comment by elondaits** [comment]
Why a license header in **each** source file? 

The ASF only requires that for things developed by them ("SOURCE FILE HEADERS FOR CODE DEVELOPED AT THE ASF") and notice the text:

"Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements."

That is not our case... we don't have a contributor license agreement with them, and we're not licensing anything specifically to them.

**Comment by porst17** [comment]
It is common practice to put the license header into each source file. See also https://www.apache.org/licenses/LICENSE-2.0#apply.

However, I have seen many OSS project just putting the `LICENSE` file into the top level directory of the git repository. Some also put the *adjusted header* to the end of the `LICENSE` file. See e.g. https://github.com/docker/docker/blob/master/LICENSE.

I'd recommend the latter. I find it tedious to add the license header to each new source file and I always forget it if I am in a hurry.

**Comment by elondaits** [comment]
OK. Yes, I worry that I'll forget but also that it makes my job harder because then I have to scroll past the license every time I want to quickly preview or open a source file. 

... But notice the second header you linked is different from the first. The second one is for people like us, while the text in the first was for ASF projects.

**Comment by porst17** [comment]
Regarding ASF projects: My bad. It looked similar to what I was looking for. But I didn't actually check all the details. Sorry for that.

I also created a TODO list in the issue description.

**Comment by elondaits** [comment]
Fixed in c366b734905bde945a5b020eb9010b51a535294d.
