### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by elondaits** [hilbert/hilbert-ui#20]
- Presets are mappings (station_id => cfg). Initially the cfg will be just the default app for that station under the preset, but it could be extended with more things (e.g. if the station should be turned off, etc.)
- Each preset has an ID (numerical, assigned by the system, that never changes) and a simple name, like templates in word processors...)
- Presets can be loaded, inserted, updated, deleted (Active Record semantics) and activated.
- It should be easy to create a preset with the current app setup, or a preset based on another one.
- A preset can 
    - Have stations that no longer exist (ignore)
    - Lack some stations (don't do anything to them)
- Back end interface
    - Load preset
        - In: preset_id
        - Out: (station_id => cfg)*
    - Insert preset
        - In: preset_name, (station_id => cfg)*
        - Out: preset_id, return code
    - Update preset
        - In: preset_id, preset_name, (station_id => cfg)*
        - Out: return code
    - Delete preset
        - In: preset_id
        - Out: return code
    - Activate preset
        - In: preset_id
        - Out: return code
- UI (draft)
    - Button: New preset > Requests name > New preset is selected
    - Select box: Preset list > A preset is selected
    - Actions
       - Button: Activate (selected preset)
       - Button: Save (selected preset)
       - Button: Delete (selected preset)
       - Button: Clone (selected preset) [optional feature]
    - Preset editor
        - List of stations (can be selected)
        - Select box: List of apps | Blank > Assigns the selected app (or none) to the selected stations
        - Button: Clear all assignments

**Comment by elondaits** [comment]
Implemented in 0caf2e132f57eff423a2e19896f66995d9b23032

The UI is not exactly as planned above because speed of implementation was prioritized, but the current version is not considered definitive. A better version will be implemented with some usage to better understand the feature.

**Comment by porst17** [comment]
Ok, great. Let's take a look at it in one of our upcoming meetings.

Regarding presets for missing stations: There should be at least a warning or some other mechanism to signal the user that the presets contains missing stations.

When the preset is activated, you could show a warning.
I haven't seen the preset editor yet, but maybe it can visualize stations that are in the preset but missing in the config (e.g. less saturated or whatever seems appropriate).
