### ISSUE TITLE
Check and adjust default station/exhibit label length and implement measures for overlong labels

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-ui#27]
Despite having a sensible default width for these labels, are there any problems with labels that are too long? Will they break the UI or will it just looks ugly? Is it necessary to cut off overlong labels and add ellipsis (or use something like `<marquee>`™)?

**Comment by elondaits** [comment]
Fixed in e8b4470b7b00ff4ac65a173158d66b83ac1dd313
