### ISSUE TITLE
UI on low resolution devices

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-ui#30]
When I open the UI on a vertical screen with low resolution, it will looks like this:
![grafik](https://user-images.githubusercontent.com/2445084/38499400-bb81bd50-3c07-11e8-81e3-9b61e9795477.png)

There are a couple of issues with this:
- [ ] The menu bar takes up to much vertical space. Each label is placed on a separate line, even though several ones will fit on the same line.
- [ ] The preset selection box is left-aligned, while the button for doing something with the preset is aligned to the right leaving quite some space in between such that both look disconnected.
- [ ] The notification and the console icon are hidden behind a menu drawer, but when I click on it, nothing happens. The developer console doesn't show an error.

I tested it on my Mac with Firefox 59.02, Chrome 65 and on my Samsung Galaxy S4 with a Chrome 64 Webview based browser and the behavior is consistent.

**Comment by elondaits** [comment]
Yes, this is not a bug. I haven’t adjusted the UI to work on mobile screens yet because there were higher priority things to work on. This is on my To-Do already

**Comment by elondaits** [comment]
Implemented in 895d3d9b89758067d0fded4d33015b4d7c784e1e
