### ISSUE TITLE
UI scaling on mobile devices

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-ui#31]
I tested the UI on my Samsung Galaxy S4 with Firefox Mobile 59. The fonts are tiny and the UI is not usable. The UI does not switch to the mode shown in #30. A similar behavior occurs if I open the UI in Chrome (Desktop) and switch to device emulation afterwards:

![bildschirmfoto 2018-04-09 um 15 24 49](https://user-images.githubusercontent.com/2445084/38500265-34501bb2-3c0a-11e8-8bf9-3d89a16b15dd.png)

After some time, it switches to the other view, but not immediately. On Firefox Mobile, the switching never happens.

**Comment by elondaits** [comment]
Yes, this is not a bug. I haven’t adjusted the UI to work on mobile screens yet because there were higher priority things to work on. This is on my To-Do already.

**Comment by elondaits** [comment]
Implemented in 895d3d9b89758067d0fded4d33015b4d7c784e1e
