### ISSUE TITLE
Log for app_change should contain app names

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-ui#32]
If I change an app, the log looks like this:

![grafik](https://user-images.githubusercontent.com/2445084/38500516-efa55f58-3c0a-11e8-9d7e-c13448db78b6.png)

But this does not give a hint about the app that a station ran before and which one it is supposed to run now. After switching apps several times, the message "App changed" becomes even less useful because as a user you don't know the history.

I propose to change the message to "App changed from 'App1' to 'App2'".

**Comment by elondaits** [comment]
Fixed in 542e1ccf52e13943a1e1be3973e8e601d9ddf946
