### ISSUE TITLE
Suggestion: show "Hilbert Dashboard" as title

### ISSUE THREAD

**Issue by vga101** [hilbert/hilbert-ui#35]
Currently the UI shows simply "Hilbert" on the top of the page and also as browser page title. Since people / we generally call it Dashboard and also to make a distinction to the general system name, wouldn't it be clearer to call it "Hilbert Dashboard?

**Comment by elondaits** [comment]
I don't like calling it a "Dashboard" because dashboards usually are mostly informative of status... this is more like a control panel... but I guess it's what everyone has been calling it since forever, so to late it to fight it 🙃

Fixed in b7e438b1e21e17755e973a11a2ea9c9daf46a7f4
