### ISSUE TITLE
Change the wording of of the UI "log" feature

### ISSUE THREAD

**Issue by elondaits** [hilbert/hilbert-ui#5]
The UI has a "Show log" button which produces a list of system events. It **is** a log of sorts (intended for users), but it could be confused with the server's log, which is a traditional UNIX log for system administrators and developers and shows system-level messages. Specially if this log is made accesible through the UI in the future.

Change the naming (to "Events", maybe) so that "log" only refers to the low level logs.

**Comment by porst17** [comment]
My two cents: *Event log* or *Past events*

**Comment by elondaits** [comment]
Yes... I would try to avoid the word "log" altogether if possible. Windows uses "Event viewer" for its feature, although it's actually the equivalent of UNIX's system.log. Drupal calls it "Watchdog" (??!). Past Events is probably better.

**Comment by elondaits** [comment]
Fixed in 82136cdfecab3e4309432ea93ec6aafc766797d6
